### ISSUE TITLE
Add support for Hermes-bytecode jsbundle

### ISSUE THREAD

**Issue by PoomSmart** [NotZoeyDev/jsbundletools#1]
Referring to the motivation of [`hbctool`](https://github.com/bongtrop/hbctool), React Native applications can choose to opt in for Hermes. The compiled app now has "HBC" header and not "RAM", see supported headers [here](https://github.com/facebook/react-native/blob/main/ReactCommon/cxxreact/JSBundleType.cpp#L16). `jsbundletools` will need to adopt `hbctool` somehow.

**Comment by NotZoeyDev** [comment]
We'll have to figure out the format eventually to add support to the tool, I'll eventually rewrite the tool to support the 3 format that JSBundles may have.
